export const GET_DATA_REQUEST = 'GET_DATA_REQUEST';
export const GET_DATA_RECEIVE = 'GET_DATA_RECEIVE';
export const LOGIN_DISPATCH = 'LOGIN_DISPATCH';
export const LOGIN_USER_SAGA_SUCCESS = 'LOGIN_USER_SAGA_SUCCESS';